version: 2.1

orbs:
  codecov: codecov/codecov@1.1.5

jobs:
  unit-tests:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - codecov/upload:
          file: coverage/coverage-final.json

workflows:
  test:
    jobs:
      - unit-tests
